module.exports = {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './packages/alert/*.{vue,js,ts,jsx,tsx}',
    './packages/app-bar/*.{vue,js,ts,jsx,tsx}',
    './packages/badge/*.{vue,js,ts,jsx,tsx}',
    './packages/breadcrumbs/*.{vue,js,ts,jsx,tsx}',
    './packages/button/*.{vue,js,ts,jsx,tsx}',
    './packages/card/*.{vue,js,ts,jsx,tsx}',
    './packages/checkbox/*.{vue,js,ts,jsx,tsx}',
    './packages/collapsible/*.{vue,js,ts,jsx,tsx}',
    './packages/container/*.{vue,js,ts,jsx,tsx}',
    './packages/dropdown/*.{vue,js,ts,jsx,tsx}',
    './packages/editor/*.{vue,js,ts,jsx,tsx}',
    './packages/file-input/*.{vue,js,ts,jsx,tsx}',
    './packages/form-group/*.{vue,js,ts,jsx,tsx}',
    './packages/form-select/*.{vue,js,ts,jsx,tsx}',
    './packages/layouts/*.{vue,js,ts,jsx,tsx}',
    './packages/logo/*.{vue,js,ts,jsx,tsx}',
    './packages/menu/*.{vue,js,ts,jsx,tsx}',
    './packages/menus/*.{vue,js,ts,jsx,tsx}',
    './packages/modal/*.{vue,js,ts,jsx,tsx}',
    './packages/multi-select/*.{vue,js,ts,jsx,tsx}',
    './packages/nav-drawer/*.{vue,js,ts,jsx,tsx}',
    './packages/navbar/*.{vue,js,ts,jsx,tsx}',
    './packages/pages/*.{vue,js,ts,jsx,tsx}',
    './packages/pagination/*.{vue,js,ts,jsx,tsx}',
    './packages/progress/*.{vue,js,ts,jsx,tsx}',
    './packages/radio/*.{vue,js,ts,jsx,tsx}',
    './packages/select/*.{vue,js,ts,jsx,tsx}',
    './packages/services/*.{vue,js,ts,jsx,tsx}',
    './packages/spinner/*.{vue,js,ts,jsx,tsx}',
    './packages/stats/*.{vue,js,ts,jsx,tsx}',
    './packages/switch/*.{vue,js,ts,jsx,tsx}',
    './packages/table/*.{vue,js,ts,jsx,tsx}',
    './packages/tabs/*.{vue,js,ts,jsx,tsx}',
    './packages/tailwind-config/*.{vue,js,ts,jsx,tsx}',
    './packages/textarea/*.{vue,js,ts,jsx,tsx}',
    './packages/theme/*.{vue,js,ts,jsx,tsx}',
    './packages/toast/*.{vue,js,ts,jsx,tsx}',
    './packages/tooltip/*.{vue,js,ts,jsx,tsx}',
  ],
  presets: [require('./packages/tailwind-config/preset')],
  plugins: [
    require('./packages/button/plugin')
  ]
};
