module.exports = {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/alert/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/app-bar/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/badge/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/breadcrumbs/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/button/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/card/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/collapsible/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/container/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/dropdown/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/editor/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/file-input/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/form-group/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/form-select/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/layouts/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/logo/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/menu/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/menus/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/modal/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/multi-select/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/nav-drawer/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/navbar/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/pages/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/pagination/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/progress-bar/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/radio/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/select/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/services/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/spinner/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/stats/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/switch/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/table/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/tabs/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/tailwind-config/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/textarea/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/theme/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/toast/*.{vue,js,ts,jsx,tsx}',
    '@morpheme/tooltip/*.{vue,js,ts,jsx,tsx}',
  ],
  presets: [require('@morpheme/tailwind-config/preset')],
  plugins: [require('@morpheme/button/plugin')],
};
