module.exports = {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/alert/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/app-bar/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/badge/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/breadcrumbs/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/button/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/card/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/collapsible/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/container/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/dropdown/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/editor/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/file-input/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/form-group/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/form-select/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/layouts/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/logo/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/menu/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/menus/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/modal/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/multi-select/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/nav-drawer/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/navbar/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/pages/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/pagination/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/progress-bar/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/radio/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/select/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/services/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/spinner/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/stats/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/switch/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/table/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/tabs/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/tailwind-config/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/textarea/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/theme/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/toast/*.{vue,js,ts,jsx,tsx}',
    '@gits-id/tooltip/*.{vue,js,ts,jsx,tsx}',
  ],
  presets: [require('@gits-id/tailwind-config/preset')],
  plugins: [
    require('@gits-id/button/plugin')
  ]
};
