export * from './types';
export * from './variants';
export * from './api';
export {default} from './VTabs.vue';
export {default as VTabs} from './VTabs.vue';
export {default as VTab} from './VTab.vue';
export {default as VTabsSlider} from './VTabsSlider.vue';
export {default as VTabGroup} from './VTabGroup.vue';
export {default as VTabItem} from './VTabItem.vue';
export {default as VTabList} from './VTabList.vue';
export {default as VTabPanel} from './VTabPanel.vue';
export {default as VTabPanels} from './VTabPanels.vue';
