// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AppMenus: typeof import('./src/components/AppMenus.vue')['default']
    Docs: typeof import('./src/components/Docs.vue')['default']
    DocsTable: typeof import('./src/components/DocsTable.vue')['default']
    DocsTitle: typeof import('./src/components/DocsTitle.vue')['default']
    HamburgerMenu: typeof import('./src/components/HamburgerMenu.vue')['default']
    HamurgerMenu: typeof import('./src/components/HamurgerMenu.vue')['default']
  }
}

export { }
