// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ComponentLayout: typeof import('./src/components/ComponentLayout.vue')['default']
    HomeLayout: typeof import('./src/components/HomeLayout.vue')['default']
  }
}

export { }
