// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    AppMenus: typeof import('./src/components/AppMenus.vue')['default']
    BurgerMenu: typeof import('./src/components/BurgerMenu.vue')['default']
    ComponentLayout: typeof import('./src/components/ComponentLayout.vue')['default']
    HamurgerMenu: typeof import('./src/components/HamurgerMenu.vue')['default']
    HomeLayout: typeof import('./src/components/HomeLayout.vue')['default']
  }
}

export { }
