// Import all dark SCSS files that exist
import './components/alert/VAlert.dark.scss';
import './components/app-bar/VAppBar.dark.scss';
import './components/autocomplete/VAutocomplete.dark.scss';
import './components/avatar/Avatar.dark.scss';
import './components/badge/VBadge.dark.scss';
import './components/bottom-sheets/BottomSheet.dark.scss';
import './components/breadcrumbs/VBreadcrumbs.dark.scss';
import './components/button/VBtn.dark.scss';
import './components/card/VCard.dark.scss';
import './components/dropdown/Dropdown.dark.scss';
import './components/forms/forms.dark.scss';
import './components/forms/checkbox/VCheckbox.dark.scss';
import './components/forms/radio/VRadio.dark.scss';
import './components/forms/radio/VRadioGroup.dark.scss';
import './components/icon/Icon.dark.scss';
import './components/list/List.dark.scss';
import './components/menus/VMenus.dark.scss';
import './components/modal/VModal.dark.scss';
import './components/multi-select/VMultiSelect.dark.scss';
import './components/nav-drawer/NavDrawer.dark.scss';
import './components/pagination/VPagination.dark.scss';
import './components/progress/VProgressBar.dark.scss';
import './components/select/VSelect.dark.scss';
import './components/shimmer/Shimmer.dark.scss';
import './components/switch/VSwitch.dark.scss';
import './components/table/VDataTable.dark.scss';
import './components/table/VDataTablePagination.dark.scss';
import './components/tabs/VTabs.dark.scss';
import './components/timeline/VTimeline.dark.scss';

// Re-export all components from their directories
export * from './components/alert';
export * from './components/app-bar';
export * from './components/app-shell';
export * from './components/autocomplete';
export * from './components/avatar';
export * from './components/badge';
export * from './components/banner';
export * from './components/bottom-navigation';
export * from './components/bottom-sheets';
export * from './components/breadcrumbs';
export * from './components/button';
export * from './components/card';
export * from './components/collapsible';
export * from './components/command';
export * from './components/container';
export * from './components/divider';
export * from './components/dropdown';
export * from './components/forms';
export * from './components/icon';
export * from './components/list';
export * from './components/menu';
export * from './components/menus';
export * from './components/modal';
export * from './components/multi-select';
export * from './components/nav-drawer';
export * from './components/navbar';
export * from './components/pagination';
export * from './components/popover';
export * from './components/progress';
export * from './components/progress-circlular';
export * from './components/rating';
export { VSelect } from './components/select';
export * from './components/shimmer';
export * from './components/spinner';
export * from './components/stats';
export * from './components/steppers';
export * from './components/switch';
export * from './components/table';
export * from './components/tabs';
export * from './components/text';
export * from './components/timeline';
export * from './components/toast';
export * from './components/tooltip';

// Export legacy items
export * from './colors';
export * from './component-resolver';
