// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AsyncComp: typeof import('./components/AsyncComp.vue')['default']
    AsyncWrapper: typeof import('./components/AsyncWrapper.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    TableActions: typeof import('./components/TableActions.vue')['default']
    ToastMessage: typeof import('./components/ToastMessage.vue')['default']
    VIcon: typeof import('./components/VIcon/VIcon.vue')['default']
  }
}

export { }
